name: atmos1
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - geopandas
  - cartopy
  - xarray
  - scikit-learn
  - statsmodels
  - jupyterlab
  - ipykernel
  - ipython
  - geographiclib
  - herbie-data
  - pynio
  - pytz
  - pysolar
  - plotly
  - netcdf4
  - cdo
  - python-cdo
  - gitpython
  - pyarrow
  - dask
  - xesmf
  - boto3
  - pip
  - pip:
    - simplekml
    - pylr2
    - windrose
