import matplotlib.pyplot as plt
import pandas as pd

#Declare functions
def plot_reg_on_ax(ax,reg_details,permil = False,labsize = 10,color = 'black'):
    '''Plots a regression line and its details on a matplotlib ax and legend
    
    Args:
    ax (axis from plt): a plt ax object on which to plot
    reg_details (dict) : details of the regression, generated by ac.lin_regress_2()
    
    Returns:
    ax : plt ax object with the regression line and legend plotted
    '''
    r2_val = reg_details['r2']
    if permil:
        slope_val = reg_details['slope']*1000 #get the "per mille" value by multiplying by 1000
        yint_val = reg_details['yint']*1000
    else:
        slope_val = reg_details['slope']
        yint_val = reg_details['yint']
                               
    annotation = f"R2={r2_val:.2}\n"
    annotation += f"slope={slope_val:.5}"
    if permil:
        annotation +=  "$^o/_{oo}$"
    annotation += '\n'
    annotation += f"y_int={yint_val:.3}"
    if permil:
        annotation +=  "$^o/_{oo}$"

    ax.plot(reg_details['x_regr_line'],reg_details['y_regr_line'],label = annotation,c = color)
    leg = ax.legend(handlelength=0, handletextpad=0, fancybox=True,fontsize = labsize)
    for item in leg.legend_handles:
        item.set_visible(False)
    return ax