# ------------------------------------------------------------------------------
# Unified GRA2PES + Regridding Configuration
#
# This YAML file contains user-editable configuration for:
# 1. Downloading and managing GRA2PES emission data
# 2. Defining regridding behavior and output resolution
#
# These values are loaded dynamically by the Python config classes.
# ------------------------------------------------------------------------------

# Months and years to download or process
months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
years: [2021]

# Source and credentials for data download
data_source: ftp  # Options: 'ftp' or 'https'
ftp_credentials_path: /uufs/chpc.utah.edu/common/home/u0890904/credentials/ftp_gra2pes_credentials2.txt

# File storage configuration
parent_path: /uufs/chpc.utah.edu/common/home/lin-group9/agm/inventories/GRA2PES_2
base_id: base_v1.0  # Used in naming and directory structure

# Optional special-case configuration for extra data types (e.g., methane)
extra_id_details:
  methane:
    folder_name: v1_methane_beta
    years: [2021]

# Regridding configuration
regrid:
  lat_spacing: 0.025             # Latitude resolution (degrees)
  lon_spacing: 0.025             # Longitude resolution (degrees)
  lat_center_range: [18.95, 58.05]     # Latitude center extent
  lon_center_range: [-138.05, -58.95]  # Longitude center extent
  method: conservative           # Regridding interpolation method
  input_dims: ["south_north", "west_east"]  # Original dimension names in input files
  weights_file: create           # Option to generate or reuse weights file

  # Optional NetCDF encoding settings (can be commented out if unused)
  # encoding_details:
  #   zlib: true
  #   complevel: 1
  #   shuffle: true
  #   chunksizes: [24, 1, 100, 100]  # Example chunk size for (hour, vertical, lat, lon)
